[project]
name = "stacks-project"
requirements = []
[contracts.marketplace]
path = "contracts/marketplace.clar"
depends_on = ["sip009-nft-trait"]

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []

[contracts.token-A]
path = "contracts/token-A.clar"
depends_on = ["sip009-nft-trait"]
